"""PR Creator for BugHawk - Creates pull requests for automated fixes."""

import os
import re
from abc import ABC, abstractmethod
from dataclasses import dataclass
from enum import Enum
from typing import Dict, List, Optional

from bughawk.core.models import FixProposal, SentryIssue
from bughawk.sentry.client import SentryClient
from bughawk.utils.logger import get_logger

logger = get_logger(__name__)


class PRPlatform(str, Enum):
    """Supported PR platforms."""

    GITHUB = "github"
    GITLAB = "gitlab"
    BITBUCKET = "bitbucket"


class PRCreatorError(Exception):
    """Base exception for PR creator errors."""

    pass


class PRAuthenticationError(PRCreatorError):
    """Authentication failed with the platform."""

    pass


class PRCreationError(PRCreatorError):
    """Failed to create pull request."""

    pass


class PRNotFoundError(PRCreatorError):
    """Pull request not found."""

    pass


@dataclass
class PRInfo:
    """Information about a created pull request."""

    url: str
    number: int
    title: str
    platform: PRPlatform
    repo_full_name: str
    head_branch: str
    base_branch: str
    state: str = "open"


class BasePRCreator(ABC):
    """Abstract base class for PR creators."""

    platform: PRPlatform

    @abstractmethod
    def create_pull_request(
        self,
        repo_full_name: str,
        head_branch: str,
        base_branch: str,
        fix_proposal: FixProposal,
        issue: SentryIssue,
        reviewers: Optional[List[str]] = None,
        labels: Optional[List[str]] = None,
    ) -> str:
        """Create a pull request for the fix.

        Args:
            repo_full_name: Full repository name (e.g., "owner/repo").
            head_branch: Branch containing the fix.
            base_branch: Branch to merge into.
            fix_proposal: The proposed fix details.
            issue: The Sentry issue being fixed.
            reviewers: Optional list of reviewer usernames.
            labels: Optional list of labels to apply.

        Returns:
            URL of the created pull request.
        """
        pass

    @abstractmethod
    def add_comment_to_pr(self, pr_url: str, comment: str) -> bool:
        """Add a comment to a pull request.

        Args:
            pr_url: URL of the pull request.
            comment: Comment text to add.

        Returns:
            True if comment was added successfully.
        """
        pass

    @abstractmethod
    def get_pr_info(self, pr_url: str) -> PRInfo:
        """Get information about a pull request.

        Args:
            pr_url: URL of the pull request.

        Returns:
            PRInfo with pull request details.
        """
        pass

    def format_pr_body(
        self,
        fix_proposal: FixProposal,
        issue: SentryIssue,
        pattern_name: Optional[str] = None,
        analysis: Optional[str] = None,
    ) -> str:
        """Format the pull request body.

        Args:
            fix_proposal: The proposed fix details.
            issue: The Sentry issue being fixed.
            pattern_name: Name of matched error pattern if any.
            analysis: Root cause analysis text.

        Returns:
            Formatted markdown body for the PR.
        """
        # Build Sentry URL
        sentry_url = issue.metadata.get(
            "url", f"https://sentry.io/issues/{issue.id}/"
        )

        # Format confidence as stars
        confidence = fix_proposal.confidence_score
        stars = "⭐" * int(confidence * 5)
        if not stars:
            stars = "☆"

        # Format diff preview (truncate if too long)
        diff_preview = self._format_diff_preview(fix_proposal.code_changes)

        # Build validation checklist
        validation_items = [
            "- [x] Syntax check passed",
        ]
        if pattern_name:
            validation_items.append(f"- [x] Pattern matched: {pattern_name}")
        else:
            validation_items.append("- [ ] Pattern matched: (no pattern)")
        validation_items.append("- [ ] Tests passed (run CI to verify)")

        validation_section = "\n".join(validation_items)

        # Build the full body
        body = f"""## 🦅 BugHawk Automated Fix

**Sentry Issue:** [#{issue.id}]({sentry_url})
**Confidence Score:** {confidence:.2f}/1.0 {stars}

### 🎯 Problem Identified
{issue.title}

{self._format_issue_details(issue)}

### 🔍 Root Cause Analysis
{analysis or fix_proposal.explanation or "Analysis based on error patterns and code context."}

### 💊 Proposed Fix
{fix_proposal.fix_description}

### 📝 Changes
```diff
{diff_preview}
```

### ✅ Validation
{validation_section}

---
*This PR was automatically generated by BugHawk 🦅*
*Please review carefully before merging*
"""
        return body

    def format_pr_title(self, issue: SentryIssue) -> str:
        """Format the pull request title.

        Args:
            issue: The Sentry issue being fixed.

        Returns:
            Formatted PR title.
        """
        # Truncate title if too long
        max_title_len = 50
        title = issue.title
        if len(title) > max_title_len:
            title = title[: max_title_len - 3] + "..."

        return f"fix: 🦅 [Sentry #{issue.id}] {title}"

    def _format_diff_preview(
        self, code_changes: Dict[str, str], max_lines: int = 50
    ) -> str:
        """Format code changes as a diff preview.

        Args:
            code_changes: Dictionary of file paths to diffs.
            max_lines: Maximum number of lines to show.

        Returns:
            Formatted diff string.
        """
        if not code_changes:
            return "No changes"

        lines: List[str] = []
        total_lines = 0

        for file_path, diff in code_changes.items():
            # Add file header if it looks like a unified diff
            if not diff.startswith("---") and not diff.startswith("diff"):
                lines.append(f"--- a/{file_path}")
                lines.append(f"+++ b/{file_path}")

            diff_lines = diff.strip().split("\n")
            for line in diff_lines:
                if total_lines >= max_lines:
                    lines.append(f"... ({len(diff_lines) - total_lines} more lines)")
                    break
                lines.append(line)
                total_lines += 1

            if total_lines >= max_lines:
                break

        return "\n".join(lines)

    def _format_issue_details(self, issue: SentryIssue) -> str:
        """Format additional issue details.

        Args:
            issue: The Sentry issue.

        Returns:
            Formatted issue details.
        """
        details: List[str] = []

        if issue.culprit:
            details.append(f"**Location:** `{issue.culprit}`")

        if issue.count > 0:
            details.append(f"**Occurrences:** {issue.count:,}")

        if issue.first_seen and issue.last_seen:
            details.append(f"**First seen:** {issue.first_seen.strftime('%Y-%m-%d %H:%M')}")
            details.append(f"**Last seen:** {issue.last_seen.strftime('%Y-%m-%d %H:%M')}")

        if issue.level:
            details.append(f"**Severity:** {issue.level.value}")

        return "\n".join(details) if details else ""


class GitHubPRCreator(BasePRCreator):
    """GitHub pull request creator using PyGithub."""

    platform = PRPlatform.GITHUB

    DEFAULT_LABELS = ["bughawk", "bug", "automated-fix"]

    def __init__(
        self,
        token: Optional[str] = None,
        sentry_client: Optional[SentryClient] = None,
    ):
        """Initialize GitHub PR creator.

        Args:
            token: GitHub personal access token. Uses GITHUB_TOKEN env if not provided.
            sentry_client: Optional Sentry client for linking issues.
        """
        self.token = token or os.environ.get("GITHUB_TOKEN")
        if not self.token:
            raise PRAuthenticationError(
                "GitHub token not provided. Set GITHUB_TOKEN environment variable "
                "or pass token to constructor."
            )

        self.sentry_client = sentry_client
        self._github = None
        self._init_github()

    def _init_github(self) -> None:
        """Initialize PyGithub client."""
        try:
            from github import Github, GithubException

            self._github = Github(self.token)
            self._GithubException = GithubException
            # Verify authentication
            _ = self._github.get_user().login
        except ImportError:
            raise PRCreatorError(
                "PyGithub not installed. Install with: pip install PyGithub"
            )
        except Exception as e:
            raise PRAuthenticationError(f"GitHub authentication failed: {e}")

    def create_pull_request(
        self,
        repo_full_name: str,
        head_branch: str,
        base_branch: str,
        fix_proposal: FixProposal,
        issue: SentryIssue,
        reviewers: Optional[List[str]] = None,
        labels: Optional[List[str]] = None,
        pattern_name: Optional[str] = None,
        analysis: Optional[str] = None,
        draft: bool = False,
    ) -> str:
        """Create a GitHub pull request.

        Args:
            repo_full_name: Full repository name (e.g., "owner/repo").
            head_branch: Branch containing the fix.
            base_branch: Branch to merge into.
            fix_proposal: The proposed fix details.
            issue: The Sentry issue being fixed.
            reviewers: Optional list of reviewer usernames.
            labels: Optional list of labels to apply.
            pattern_name: Name of matched error pattern.
            analysis: Root cause analysis text.
            draft: Whether to create as draft PR.

        Returns:
            URL of the created pull request.

        Raises:
            PRCreationError: If PR creation fails.
        """
        try:
            repo = self._github.get_repo(repo_full_name)

            # Format PR content
            title = self.format_pr_title(issue)
            body = self.format_pr_body(
                fix_proposal, issue, pattern_name=pattern_name, analysis=analysis
            )

            # Create the pull request
            pr = repo.create_pull(
                title=title,
                body=body,
                head=head_branch,
                base=base_branch,
                draft=draft,
            )

            logger.info(f"Created PR #{pr.number}: {pr.html_url}")

            # Add labels
            pr_labels = labels or self.DEFAULT_LABELS
            self._add_labels(pr, pr_labels)

            # Request reviewers
            if reviewers:
                self._request_reviewers(pr, reviewers)

            # Link to Sentry issue
            self._link_to_sentry(issue.id, pr.html_url)

            return pr.html_url

        except self._GithubException as e:
            error_msg = str(e)
            if e.status == 404:
                raise PRCreationError(
                    f"Repository '{repo_full_name}' not found or not accessible"
                )
            elif e.status == 422:
                # Validation error - often duplicate PR
                if "already exists" in error_msg.lower():
                    raise PRCreationError(
                        f"A PR for branch '{head_branch}' already exists"
                    )
                raise PRCreationError(f"Validation error: {error_msg}")
            else:
                raise PRCreationError(f"Failed to create PR: {error_msg}")
        except Exception as e:
            raise PRCreationError(f"Unexpected error creating PR: {e}")

    def add_comment_to_pr(self, pr_url: str, comment: str) -> bool:
        """Add a comment to a GitHub pull request.

        Args:
            pr_url: URL of the pull request.
            comment: Comment text to add.

        Returns:
            True if comment was added successfully.
        """
        try:
            repo_name, pr_number = self._parse_pr_url(pr_url)
            repo = self._github.get_repo(repo_name)
            pr = repo.get_pull(pr_number)
            pr.create_issue_comment(comment)
            logger.info(f"Added comment to PR #{pr_number}")
            return True
        except self._GithubException as e:
            logger.error(f"Failed to add comment to PR: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error adding comment: {e}")
            return False

    def get_pr_info(self, pr_url: str) -> PRInfo:
        """Get information about a GitHub pull request.

        Args:
            pr_url: URL of the pull request.

        Returns:
            PRInfo with pull request details.

        Raises:
            PRNotFoundError: If PR is not found.
        """
        try:
            repo_name, pr_number = self._parse_pr_url(pr_url)
            repo = self._github.get_repo(repo_name)
            pr = repo.get_pull(pr_number)

            return PRInfo(
                url=pr.html_url,
                number=pr.number,
                title=pr.title,
                platform=PRPlatform.GITHUB,
                repo_full_name=repo_name,
                head_branch=pr.head.ref,
                base_branch=pr.base.ref,
                state=pr.state,
            )
        except self._GithubException as e:
            if e.status == 404:
                raise PRNotFoundError(f"PR not found: {pr_url}")
            raise PRCreatorError(f"Failed to get PR info: {e}")

    def link_sentry_issue(
        self,
        issue_id: str,
        pr_url: str,
        tags: Optional[Dict[str, str]] = None,
    ) -> bool:
        """Link a Sentry issue to a pull request.

        Args:
            issue_id: Sentry issue ID.
            pr_url: URL of the pull request.
            tags: Optional additional tags to add.

        Returns:
            True if linking was successful.
        """
        return self._link_to_sentry(issue_id, pr_url, tags)

    def _add_labels(self, pr, labels: List[str]) -> None:
        """Add labels to a pull request.

        Args:
            pr: PyGithub PullRequest object.
            labels: List of label names.
        """
        try:
            # Get or create labels
            repo = pr.base.repo
            existing_labels = {label.name for label in repo.get_labels()}

            for label_name in labels:
                if label_name not in existing_labels:
                    # Create label with default color
                    try:
                        repo.create_label(
                            name=label_name,
                            color=self._get_label_color(label_name),
                        )
                    except self._GithubException:
                        pass  # Label might already exist

            pr.add_to_labels(*labels)
            logger.debug(f"Added labels: {labels}")
        except Exception as e:
            logger.warning(f"Failed to add labels: {e}")

    def _request_reviewers(self, pr, reviewers: List[str]) -> None:
        """Request reviewers for a pull request.

        Args:
            pr: PyGithub PullRequest object.
            reviewers: List of reviewer usernames.
        """
        try:
            pr.create_review_request(reviewers=reviewers)
            logger.debug(f"Requested reviewers: {reviewers}")
        except self._GithubException as e:
            logger.warning(f"Failed to request reviewers: {e}")

    def _link_to_sentry(
        self,
        issue_id: str,
        pr_url: str,
        tags: Optional[Dict[str, str]] = None,
    ) -> bool:
        """Add link to PR in Sentry issue.

        Args:
            issue_id: Sentry issue ID.
            pr_url: URL of the pull request.
            tags: Optional additional tags.

        Returns:
            True if successful.
        """
        if not self.sentry_client:
            logger.debug("No Sentry client configured, skipping issue link")
            return False

        try:
            comment = f"""🦅 **BugHawk Fix Submitted**

A pull request has been created to fix this issue:
{pr_url}

Please review and merge if the fix looks correct.
"""
            self.sentry_client.add_comment(issue_id, comment)
            logger.info(f"Linked PR to Sentry issue {issue_id}")
            return True
        except Exception as e:
            logger.warning(f"Failed to link PR to Sentry issue: {e}")
            return False

    def _parse_pr_url(self, pr_url: str) -> tuple:
        """Parse repository name and PR number from URL.

        Args:
            pr_url: GitHub PR URL.

        Returns:
            Tuple of (repo_full_name, pr_number).

        Raises:
            PRCreatorError: If URL format is invalid.
        """
        # Match: https://github.com/owner/repo/pull/123
        pattern = r"github\.com/([^/]+/[^/]+)/pull/(\d+)"
        match = re.search(pattern, pr_url)

        if not match:
            raise PRCreatorError(f"Invalid GitHub PR URL: {pr_url}")

        return match.group(1), int(match.group(2))

    def _get_label_color(self, label_name: str) -> str:
        """Get color for a label.

        Args:
            label_name: Name of the label.

        Returns:
            Hex color code (without #).
        """
        colors = {
            "bughawk": "D4A017",  # Hawk gold
            "bug": "d73a4a",  # Red
            "automated-fix": "0e8a16",  # Green
            "needs-review": "fbca04",  # Yellow
        }
        return colors.get(label_name, "ededed")


class GitLabPRCreator(BasePRCreator):
    """GitLab merge request creator using python-gitlab."""

    platform = PRPlatform.GITLAB

    DEFAULT_LABELS = ["bughawk", "bug", "automated-fix"]

    def __init__(
        self,
        token: Optional[str] = None,
        gitlab_url: str = "https://gitlab.com",
        sentry_client: Optional[SentryClient] = None,
    ):
        """Initialize GitLab MR creator.

        Args:
            token: GitLab personal access token. Uses GITLAB_TOKEN env if not provided.
            gitlab_url: GitLab instance URL.
            sentry_client: Optional Sentry client for linking issues.
        """
        self.token = token or os.environ.get("GITLAB_TOKEN")
        self.gitlab_url = gitlab_url.rstrip("/")
        self.sentry_client = sentry_client
        self._gitlab = None
        self._GitlabError = None

        if not self.token:
            raise PRAuthenticationError(
                "GitLab token not provided. Set GITLAB_TOKEN environment variable "
                "or pass token to constructor."
            )

        self._init_gitlab()

    def _init_gitlab(self) -> None:
        """Initialize python-gitlab client."""
        try:
            import gitlab
            from gitlab.exceptions import GitlabError

            self._gitlab = gitlab.Gitlab(self.gitlab_url, private_token=self.token)
            self._GitlabError = GitlabError
            # Verify authentication
            self._gitlab.auth()
        except ImportError:
            raise PRCreatorError(
                "python-gitlab not installed. Install with: pip install python-gitlab"
            )
        except Exception as e:
            raise PRAuthenticationError(f"GitLab authentication failed: {e}")

    def create_pull_request(
        self,
        repo_full_name: str,
        head_branch: str,
        base_branch: str,
        fix_proposal: FixProposal,
        issue: SentryIssue,
        reviewers: Optional[List[str]] = None,
        labels: Optional[List[str]] = None,
        pattern_name: Optional[str] = None,
        analysis: Optional[str] = None,
        draft: bool = False,
    ) -> str:
        """Create a GitLab merge request.

        Args:
            repo_full_name: Full project path (e.g., "group/project" or "group/subgroup/project").
            head_branch: Branch containing the fix.
            base_branch: Branch to merge into.
            fix_proposal: The proposed fix details.
            issue: The Sentry issue being fixed.
            reviewers: Optional list of reviewer usernames.
            labels: Optional list of labels to apply.
            pattern_name: Name of matched error pattern.
            analysis: Root cause analysis text.
            draft: Whether to create as draft MR.

        Returns:
            URL of the created merge request.

        Raises:
            PRCreationError: If MR creation fails.
        """
        try:
            # Get the project (use URL-encoded path)
            project = self._gitlab.projects.get(repo_full_name)

            # Format MR content
            title = self.format_pr_title(issue)
            if draft:
                title = f"Draft: {title}"

            body = self.format_pr_body(
                fix_proposal, issue, pattern_name=pattern_name, analysis=analysis
            )

            # Create the merge request
            mr = project.mergerequests.create({
                "source_branch": head_branch,
                "target_branch": base_branch,
                "title": title,
                "description": body,
                "remove_source_branch": True,
            })

            logger.info(f"Created MR !{mr.iid}: {mr.web_url}")

            # Add labels
            mr_labels = labels or self.DEFAULT_LABELS
            self._add_labels(project, mr, mr_labels)

            # Request reviewers
            if reviewers:
                self._request_reviewers(project, mr, reviewers)

            # Link to Sentry issue
            self._link_to_sentry(issue.id, mr.web_url)

            return mr.web_url

        except self._GitlabError as e:
            error_msg = str(e)
            if "404" in error_msg:
                raise PRCreationError(
                    f"Project '{repo_full_name}' not found or not accessible"
                )
            elif "already exists" in error_msg.lower():
                raise PRCreationError(
                    f"A merge request for branch '{head_branch}' already exists"
                )
            else:
                raise PRCreationError(f"Failed to create MR: {error_msg}")
        except Exception as e:
            raise PRCreationError(f"Unexpected error creating MR: {e}")

    def add_comment_to_pr(self, pr_url: str, comment: str) -> bool:
        """Add a comment to a GitLab merge request.

        Args:
            pr_url: URL of the merge request.
            comment: Comment text to add.

        Returns:
            True if comment was added successfully.
        """
        try:
            project_path, mr_iid = self._parse_mr_url(pr_url)
            project = self._gitlab.projects.get(project_path)
            mr = project.mergerequests.get(mr_iid)
            mr.notes.create({"body": comment})
            logger.info(f"Added comment to MR !{mr_iid}")
            return True
        except self._GitlabError as e:
            logger.error(f"Failed to add comment to MR: {e}")
            return False
        except Exception as e:
            logger.error(f"Unexpected error adding comment: {e}")
            return False

    def get_pr_info(self, pr_url: str) -> PRInfo:
        """Get information about a GitLab merge request.

        Args:
            pr_url: URL of the merge request.

        Returns:
            PRInfo with merge request details.

        Raises:
            PRNotFoundError: If MR is not found.
        """
        try:
            project_path, mr_iid = self._parse_mr_url(pr_url)
            project = self._gitlab.projects.get(project_path)
            mr = project.mergerequests.get(mr_iid)

            return PRInfo(
                url=mr.web_url,
                number=mr.iid,
                title=mr.title,
                platform=PRPlatform.GITLAB,
                repo_full_name=project_path,
                head_branch=mr.source_branch,
                base_branch=mr.target_branch,
                state=mr.state,
            )
        except self._GitlabError as e:
            if "404" in str(e):
                raise PRNotFoundError(f"MR not found: {pr_url}")
            raise PRCreatorError(f"Failed to get MR info: {e}")

    def _add_labels(self, project, mr, labels: List[str]) -> None:
        """Add labels to a merge request.

        Args:
            project: GitLab project object.
            mr: GitLab merge request object.
            labels: List of label names.
        """
        try:
            # Get existing labels in project
            existing_labels = {label.name for label in project.labels.list(all=True)}

            # Create missing labels
            for label_name in labels:
                if label_name not in existing_labels:
                    try:
                        project.labels.create({
                            "name": label_name,
                            "color": f"#{self._get_label_color(label_name)}",
                        })
                    except self._GitlabError:
                        pass  # Label might already exist

            # Update MR with labels
            mr.labels = labels
            mr.save()
            logger.debug(f"Added labels: {labels}")
        except Exception as e:
            logger.warning(f"Failed to add labels: {e}")

    def _request_reviewers(self, project, mr, reviewers: List[str]) -> None:
        """Request reviewers for a merge request.

        Args:
            project: GitLab project object.
            mr: GitLab merge request object.
            reviewers: List of reviewer usernames.
        """
        try:
            # Get user IDs for reviewers
            reviewer_ids = []
            for username in reviewers:
                users = self._gitlab.users.list(username=username)
                if users:
                    reviewer_ids.append(users[0].id)
                else:
                    logger.warning(f"User not found: {username}")

            if reviewer_ids:
                mr.reviewer_ids = reviewer_ids
                mr.save()
                logger.debug(f"Requested reviewers: {reviewers}")
        except self._GitlabError as e:
            logger.warning(f"Failed to request reviewers: {e}")

    def _link_to_sentry(
        self,
        issue_id: str,
        mr_url: str,
        tags: Optional[Dict[str, str]] = None,
    ) -> bool:
        """Add link to MR in Sentry issue.

        Args:
            issue_id: Sentry issue ID.
            mr_url: URL of the merge request.
            tags: Optional additional tags.

        Returns:
            True if successful.
        """
        if not self.sentry_client:
            logger.debug("No Sentry client configured, skipping issue link")
            return False

        try:
            comment = f"""🦅 **BugHawk Fix Submitted**

A merge request has been created to fix this issue:
{mr_url}

Please review and merge if the fix looks correct.
"""
            self.sentry_client.add_comment(issue_id, comment)
            logger.info(f"Linked MR to Sentry issue {issue_id}")
            return True
        except Exception as e:
            logger.warning(f"Failed to link MR to Sentry issue: {e}")
            return False

    def _parse_mr_url(self, mr_url: str) -> tuple:
        """Parse project path and MR IID from URL.

        Args:
            mr_url: GitLab MR URL.

        Returns:
            Tuple of (project_path, mr_iid).

        Raises:
            PRCreatorError: If URL format is invalid.
        """
        # Match: https://gitlab.com/group/project/-/merge_requests/123
        # or: https://gitlab.com/group/subgroup/project/-/merge_requests/123
        pattern = r"gitlab[^/]*/(.+?)/-/merge_requests/(\d+)"
        match = re.search(pattern, mr_url)

        if not match:
            raise PRCreatorError(f"Invalid GitLab MR URL: {mr_url}")

        return match.group(1), int(match.group(2))

    def _get_label_color(self, label_name: str) -> str:
        """Get color for a label.

        Args:
            label_name: Name of the label.

        Returns:
            Hex color code (without #).
        """
        colors = {
            "bughawk": "D4A017",  # Hawk gold
            "bug": "d73a4a",  # Red
            "automated-fix": "0e8a16",  # Green
            "needs-review": "fbca04",  # Yellow
        }
        return colors.get(label_name, "ededed")


class BitbucketPRCreator(BasePRCreator):
    """Bitbucket pull request creator using Bitbucket REST API."""

    platform = PRPlatform.BITBUCKET

    API_BASE_URL = "https://api.bitbucket.org/2.0"

    def __init__(
        self,
        username: Optional[str] = None,
        app_password: Optional[str] = None,
        sentry_client: Optional[SentryClient] = None,
    ):
        """Initialize Bitbucket PR creator.

        Args:
            username: Bitbucket username. Uses BITBUCKET_USERNAME env if not provided.
            app_password: Bitbucket app password. Uses BITBUCKET_APP_PASSWORD env if not provided.
            sentry_client: Optional Sentry client for linking issues.
        """
        self.username = username or os.environ.get("BITBUCKET_USERNAME")
        self.app_password = app_password or os.environ.get("BITBUCKET_APP_PASSWORD")
        self.sentry_client = sentry_client
        self._session = None

        if not self.username or not self.app_password:
            raise PRAuthenticationError(
                "Bitbucket credentials not provided. Set BITBUCKET_USERNAME and "
                "BITBUCKET_APP_PASSWORD environment variables."
            )

        self._init_session()

    def _init_session(self) -> None:
        """Initialize requests session with authentication."""
        try:
            import requests

            self._session = requests.Session()
            self._session.auth = (self.username, self.app_password)

            # Verify authentication by fetching user info
            response = self._session.get(f"{self.API_BASE_URL}/user")
            if response.status_code == 401:
                raise PRAuthenticationError("Bitbucket authentication failed: Invalid credentials")
            elif response.status_code != 200:
                raise PRAuthenticationError(f"Bitbucket authentication failed: {response.text}")

        except ImportError:
            raise PRCreatorError(
                "requests not installed. Install with: pip install requests"
            )
        except PRAuthenticationError:
            raise
        except Exception as e:
            raise PRAuthenticationError(f"Bitbucket authentication failed: {e}")

    def create_pull_request(
        self,
        repo_full_name: str,
        head_branch: str,
        base_branch: str,
        fix_proposal: FixProposal,
        issue: SentryIssue,
        reviewers: Optional[List[str]] = None,
        labels: Optional[List[str]] = None,
        pattern_name: Optional[str] = None,
        analysis: Optional[str] = None,
        draft: bool = False,
    ) -> str:
        """Create a Bitbucket pull request.

        Args:
            repo_full_name: Full repository slug (e.g., "workspace/repo-slug").
            head_branch: Branch containing the fix.
            base_branch: Branch to merge into.
            fix_proposal: The proposed fix details.
            issue: The Sentry issue being fixed.
            reviewers: Optional list of reviewer account IDs or usernames.
            labels: Optional list of labels (Note: Bitbucket doesn't support labels on PRs).
            pattern_name: Name of matched error pattern.
            analysis: Root cause analysis text.
            draft: Whether to create as draft PR (Note: Bitbucket Cloud doesn't support drafts).

        Returns:
            URL of the created pull request.

        Raises:
            PRCreationError: If PR creation fails.
        """
        try:
            # Format PR content
            title = self.format_pr_title(issue)
            body = self.format_pr_body(
                fix_proposal, issue, pattern_name=pattern_name, analysis=analysis
            )

            # Bitbucket API expects workspace/repo-slug format
            url = f"{self.API_BASE_URL}/repositories/{repo_full_name}/pullrequests"

            payload = {
                "title": title,
                "description": body,
                "source": {
                    "branch": {
                        "name": head_branch,
                    },
                },
                "destination": {
                    "branch": {
                        "name": base_branch,
                    },
                },
                "close_source_branch": True,
            }

            # Add reviewers if specified
            if reviewers:
                payload["reviewers"] = self._format_reviewers(reviewers)

            response = self._session.post(url, json=payload)

            if response.status_code == 201:
                pr_data = response.json()
                pr_url = pr_data["links"]["html"]["href"]
                pr_id = pr_data["id"]
                logger.info(f"Created PR #{pr_id}: {pr_url}")

                # Link to Sentry issue
                self._link_to_sentry(issue.id, pr_url)

                return pr_url
            elif response.status_code == 404:
                raise PRCreationError(
                    f"Repository '{repo_full_name}' not found or not accessible"
                )
            elif response.status_code == 400:
                error_data = response.json()
                error_msg = error_data.get("error", {}).get("message", response.text)
                if "already exists" in error_msg.lower() or "open pull request" in error_msg.lower():
                    raise PRCreationError(
                        f"A pull request for branch '{head_branch}' already exists"
                    )
                raise PRCreationError(f"Validation error: {error_msg}")
            elif response.status_code == 401:
                raise PRAuthenticationError("Authentication failed")
            else:
                raise PRCreationError(f"Failed to create PR: {response.text}")

        except (PRCreationError, PRAuthenticationError):
            raise
        except Exception as e:
            raise PRCreationError(f"Unexpected error creating PR: {e}")

    def add_comment_to_pr(self, pr_url: str, comment: str) -> bool:
        """Add a comment to a Bitbucket pull request.

        Args:
            pr_url: URL of the pull request.
            comment: Comment text to add.

        Returns:
            True if comment was added successfully.
        """
        try:
            repo_full_name, pr_id = self._parse_pr_url(pr_url)
            url = f"{self.API_BASE_URL}/repositories/{repo_full_name}/pullrequests/{pr_id}/comments"

            payload = {
                "content": {
                    "raw": comment,
                },
            }

            response = self._session.post(url, json=payload)

            if response.status_code == 201:
                logger.info(f"Added comment to PR #{pr_id}")
                return True
            else:
                logger.error(f"Failed to add comment to PR: {response.text}")
                return False
        except Exception as e:
            logger.error(f"Unexpected error adding comment: {e}")
            return False

    def get_pr_info(self, pr_url: str) -> PRInfo:
        """Get information about a Bitbucket pull request.

        Args:
            pr_url: URL of the pull request.

        Returns:
            PRInfo with pull request details.

        Raises:
            PRNotFoundError: If PR is not found.
        """
        try:
            repo_full_name, pr_id = self._parse_pr_url(pr_url)
            url = f"{self.API_BASE_URL}/repositories/{repo_full_name}/pullrequests/{pr_id}"

            response = self._session.get(url)

            if response.status_code == 200:
                pr_data = response.json()
                return PRInfo(
                    url=pr_data["links"]["html"]["href"],
                    number=pr_data["id"],
                    title=pr_data["title"],
                    platform=PRPlatform.BITBUCKET,
                    repo_full_name=repo_full_name,
                    head_branch=pr_data["source"]["branch"]["name"],
                    base_branch=pr_data["destination"]["branch"]["name"],
                    state=pr_data["state"].lower(),
                )
            elif response.status_code == 404:
                raise PRNotFoundError(f"PR not found: {pr_url}")
            else:
                raise PRCreatorError(f"Failed to get PR info: {response.text}")
        except PRNotFoundError:
            raise
        except Exception as e:
            raise PRCreatorError(f"Failed to get PR info: {e}")

    def _format_reviewers(self, reviewers: List[str]) -> List[Dict[str, str]]:
        """Format reviewers for Bitbucket API.

        Args:
            reviewers: List of reviewer usernames or account IDs.

        Returns:
            List of reviewer dicts for Bitbucket API.
        """
        formatted = []
        for reviewer in reviewers:
            # Try to get user by username
            try:
                response = self._session.get(f"{self.API_BASE_URL}/users/{reviewer}")
                if response.status_code == 200:
                    user_data = response.json()
                    formatted.append({"uuid": user_data["uuid"]})
                else:
                    # Assume it's already a UUID
                    if reviewer.startswith("{"):
                        formatted.append({"uuid": reviewer})
                    else:
                        logger.warning(f"User not found: {reviewer}")
            except Exception as e:
                logger.warning(f"Failed to lookup user {reviewer}: {e}")
        return formatted

    def _link_to_sentry(
        self,
        issue_id: str,
        pr_url: str,
        tags: Optional[Dict[str, str]] = None,
    ) -> bool:
        """Add link to PR in Sentry issue.

        Args:
            issue_id: Sentry issue ID.
            pr_url: URL of the pull request.
            tags: Optional additional tags.

        Returns:
            True if successful.
        """
        if not self.sentry_client:
            logger.debug("No Sentry client configured, skipping issue link")
            return False

        try:
            comment = f"""🦅 **BugHawk Fix Submitted**

A pull request has been created to fix this issue:
{pr_url}

Please review and merge if the fix looks correct.
"""
            self.sentry_client.add_comment(issue_id, comment)
            logger.info(f"Linked PR to Sentry issue {issue_id}")
            return True
        except Exception as e:
            logger.warning(f"Failed to link PR to Sentry issue: {e}")
            return False

    def _parse_pr_url(self, pr_url: str) -> tuple:
        """Parse repository slug and PR ID from URL.

        Args:
            pr_url: Bitbucket PR URL.

        Returns:
            Tuple of (repo_full_name, pr_id).

        Raises:
            PRCreatorError: If URL format is invalid.
        """
        # Match: https://bitbucket.org/workspace/repo-slug/pull-requests/123
        pattern = r"bitbucket\.org/([^/]+/[^/]+)/pull-requests/(\d+)"
        match = re.search(pattern, pr_url)

        if not match:
            raise PRCreatorError(f"Invalid Bitbucket PR URL: {pr_url}")

        return match.group(1), int(match.group(2))


class PRCreator:
    """Factory class for creating platform-specific PR creators.

    Example:
        >>> creator = PRCreator.for_platform(PRPlatform.GITHUB)
        >>> pr_url = creator.create_pull_request(
        ...     repo_full_name="org/repo",
        ...     head_branch="bughawk-fix/issue-123",
        ...     base_branch="main",
        ...     fix_proposal=fix,
        ...     issue=sentry_issue,
        ... )
    """

    _creators = {
        PRPlatform.GITHUB: GitHubPRCreator,
        PRPlatform.GITLAB: GitLabPRCreator,
        PRPlatform.BITBUCKET: BitbucketPRCreator,
    }

    @classmethod
    def for_platform(
        cls,
        platform: PRPlatform,
        sentry_client: Optional[SentryClient] = None,
        **kwargs,
    ) -> BasePRCreator:
        """Create a PR creator for the specified platform.

        Args:
            platform: The git platform to use.
            sentry_client: Optional Sentry client for linking issues.
            **kwargs: Platform-specific arguments.

        Returns:
            Platform-specific PR creator instance.

        Raises:
            PRCreatorError: If platform is not supported.
        """
        creator_class = cls._creators.get(platform)
        if not creator_class:
            raise PRCreatorError(f"Unsupported platform: {platform}")

        return creator_class(sentry_client=sentry_client, **kwargs)

    @classmethod
    def from_repo_url(
        cls,
        repo_url: str,
        sentry_client: Optional[SentryClient] = None,
        **kwargs,
    ) -> BasePRCreator:
        """Create a PR creator based on repository URL.

        Args:
            repo_url: Repository URL (HTTPS or SSH).
            sentry_client: Optional Sentry client.
            **kwargs: Platform-specific arguments.

        Returns:
            Platform-specific PR creator instance.
        """
        platform = cls._detect_platform(repo_url)
        return cls.for_platform(platform, sentry_client=sentry_client, **kwargs)

    @classmethod
    def _detect_platform(cls, repo_url: str) -> PRPlatform:
        """Detect platform from repository URL.

        Args:
            repo_url: Repository URL.

        Returns:
            Detected PRPlatform.

        Raises:
            PRCreatorError: If platform cannot be detected.
        """
        url_lower = repo_url.lower()

        if "github.com" in url_lower or "github" in url_lower:
            return PRPlatform.GITHUB
        elif "gitlab" in url_lower:
            return PRPlatform.GITLAB
        elif "bitbucket" in url_lower:
            return PRPlatform.BITBUCKET
        else:
            raise PRCreatorError(
                f"Could not detect platform from URL: {repo_url}. "
                "Supported platforms: GitHub, GitLab, Bitbucket"
            )

    @classmethod
    def register_creator(
        cls,
        platform: PRPlatform,
        creator_class: type,
    ) -> None:
        """Register a custom PR creator for a platform.

        Args:
            platform: The platform to register for.
            creator_class: The creator class to use.
        """
        cls._creators[platform] = creator_class
